graph LR
    AppModule-->AuthModule
  AppModule-->ConfigHostModule
  AppModule-->ConfigModule
  AppModule-->LoggerModule
  AppModule-->MailerCoreModule
  AppModule-->MailerModule
  AppModule-->MongooseCoreModule
  AppModule-->MongooseModule
  AppModule-->SharedModule
  AppModule-->UserModule
  AuthModule-->ConfigHostModule
  AuthModule-->ConfigModule
  AuthModule-->JwtModule
  AuthModule-->MailerCoreModule
  AuthModule-->MongooseCoreModule
  AuthModule-->PassportModule
  AuthModule-->UserModule
  ConfigHostModule-->ConfigModule
  ConfigHostModule-->MailerCoreModule
  ConfigHostModule-->MongooseCoreModule
  ConfigModule-->ConfigHostModule
  ConfigModule-->ConfigModule
  ConfigModule-->MailerCoreModule
  ConfigModule-->MongooseCoreModule
  JwtModule-->ConfigHostModule
  JwtModule-->ConfigModule
  JwtModule-->MailerCoreModule
  JwtModule-->MongooseCoreModule
  LoggerModule-->ConfigHostModule
  LoggerModule-->ConfigModule
  LoggerModule-->MailerCoreModule
  LoggerModule-->MongooseCoreModule
  MailerCoreModule-->ConfigHostModule
  MailerCoreModule-->ConfigModule
  MailerCoreModule-->MongooseCoreModule
  MailerModule-->ConfigHostModule
  MailerModule-->ConfigModule
  MailerModule-->MailerCoreModule
  MailerModule-->MongooseCoreModule
  MongooseCoreModule-->ConfigHostModule
  MongooseCoreModule-->ConfigModule
  MongooseCoreModule-->MailerCoreModule
  MongooseModule-->ConfigHostModule
  MongooseModule-->ConfigModule
  MongooseModule-->MailerCoreModule
  MongooseModule-->MongooseCoreModule
  PassportModule-->ConfigHostModule
  PassportModule-->ConfigModule
  PassportModule-->MailerCoreModule
  PassportModule-->MongooseCoreModule
  SharedModule-->ConfigHostModule
  SharedModule-->ConfigModule
  SharedModule-->MailerCoreModule
  SharedModule-->MongooseCoreModule
  UserModule-->ConfigHostModule
  UserModule-->ConfigModule
  UserModule-->MailerCoreModule
  UserModule-->MongooseCoreModule
  UserModule-->MongooseModule
  UserModule-->UserSignUpDto
  UserSignUpDto-->ConfigHostModule
  UserSignUpDto-->ConfigModule
  UserSignUpDto-->MailerCoreModule
  UserSignUpDto-->MongooseCoreModule