version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        volumes:
            - ./docker/mongodb:/data/db
        logging:
            driver: 'json-file'
            options:
                max-size: '100m'
                max-file: '20'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        ports:
            - '${MONGO_PORT}:27017'
    backend:
        image: server:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: server
        restart: unless-stopped
        depends_on:
            - mongodb
        ports:
            - 5000:5000
