name: Build Packages
on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
        paths-ignore:
            - 'README.md'
            - 'LICENSE'
jobs:
    lint-prettier:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install dependencies (server)
              run: cd server && pnpm install

            - name: Run ESLint (server)
              run: cd server && pnpm lint

            - name: Run Prettier (server)
              run: cd server && pnpm format
